name: Unit tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.5.0

      - name: npm ci
        run: npm ci

      - name: run lint
        uses: wearerequired/lint-action@v1.7.0
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          auto_fix: true

      - name: mocha unit tests
        run: npm run ci